disabled_rules:
  - file_length
  - function_body_length
  - todo
  - trailing_whitespace
  - function_parameter_count
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - redundant_discardable_let
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - GroupedTableView/AppDelegate.swift
  - GroupedTableView/SceneDelegate.swift

identifier_name:
  min_length: 3
  max_length:
    warning: 30
  excluded:
    - id
    - i
    - j
    - k
    - to
large_tuple: 4
line_length: 200
trailing_comma:
  mandatory_comma: true
